apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpuchile-backend-sa
  namespace: default
  annotations:
    # Este es el rol que cre√≥ Terraform para permitir acceso a S3 y Secrets
    eks.amazonaws.com/role-arn: "arn:aws:iam::380002980493:role/gpuchile-cluster-gpuchile-backend-sa-role"
