apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpuchile-frontend.fullname" . }}-nginx-config
  labels:
    app: {{ include "gpuchile-frontend.name" . }}
data:
  default.conf: |
{{ .Files.Get "nginx.conf" | indent 4 }}
