apiVersion: v2
name: gpuchile-backend
description: FastAPI Backend for GpuChile E-commerce
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Nicolas Nunez
    email: nicolasnunezalvarez@gmail.com