apiVersion: v2
name: gpuchile-frontend
description: React Frontend for GpuChile E-commerce
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Nicolas Nunez
    email: nicolasnunezalvarez05@gmail.com